### PR TITLE
fix: adapt to upstream rename of vim.mpack.*

### LINKED ISSUE #36: Adapt to upstream rename `vim.mpack.pack` ->  `vim.mpack.encode`
...and similar for `vim.mpack.unpack`, see https://github.com/neovim/neovim/pull/16175

### PR DESCRIPTION
**Pull request by clason**
`vim.mpack.pack` -> `vim.mpack.encode`
`vim.mpack.unpack` -> `vim.mpack.decode`
https://github.com/neovim/neovim/pull/16175

closes #36

### CODE REVIEW

**Comment by lewis6991** [comment]
Need to update cachepack.lua to use the new methods names for 0.5 compat

**Comment by clason** [comment]
(CI failure is due to hard-coding the list of modules whose order is not stable and likely changed due to the LuaJIT bump on Neovim HEAD.)

**Comment by lewis6991** [comment]
No problem, I'll fix ci another time

**Comment by lewis6991** [comment]
Thanks btw

**Pull request merged**
